frontend:
  replicas: 1
  image:
    repository: 929806479990.dkr.ecr.eu-west-1.amazonaws.com/frontend
    tag: latest
    pullPolicy: 
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 70
    targetMemoryUtilizationPercentage: 80   


backend:
  replicas: 1
  image:
    repository: 929806479990.dkr.ecr.eu-west-1.amazonaws.com/backend
    tag: latest
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 70
    targetMemoryUtilizationPercentage: 80     
  db:
    host: tasks-postgres-postgresql.data.svc.cluster.local
    port: "5432"
    name: tasksdb
    user: postgres
    password: postgres   # stored in Secret
