apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-nginx-conf
data:
  nginx.conf: |
    pid /tmp/nginx.pid;
    events {}
    http {
      client_body_temp_path /tmp/nginx/client_temp;
      proxy_temp_path       /tmp/nginx/proxy_temp;
      fastcgi_temp_path     /tmp/nginx/fastcgi_temp;
      uwsgi_temp_path       /tmp/nginx/uwsgi_temp;
      scgi_temp_path        /tmp/nginx/scgi_temp;

      server {
        listen 8080;
        add_header Cache-Control "no-store";

        location / {
          root  /usr/share/nginx/html;
          index index.html;
        }

        location /api/ {
          proxy_pass http://backend:8000/;
          proxy_set_header Host $host;
          proxy_http_version 1.1;
        }
      }
    }
